217

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,3 +38,26 @@ jobs:
 
       - name: Run Integration Tests in the Background
         run: npx mocha tests/healthz.test.js &
+
+      - name: Format Packer Template
+        run: |
+
+          # Run packer fmt and capture the exit code
+           packer fmt -check .
+
+          # Check the exit code and fail the workflow if changes were made
+          if [ $? -ne 0 ]; then
+           echo "Packer template formatting check failed. Please run 'packer fmt' locally and commit the changes."
+           exit 1
+          fi
+
+      - name: Validate Packer Template
+        run: |
+          # Run packer validate and capture the exit code
+          packer validate -syntax-only .
+
+          # Check the exit code and fail the workflow if validation fails
+          if [ $? -ne 0 ]; then
+            echo "Packer template validation failed. Please ensure the template is correct before merging the pull request."
+            exit 1
+          fi
